# Generated by Django 2.0.2 on 2018-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.IntegerField(),
        ),
    ]
