# Generated by Django 2.0.2 on 2018-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180610_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
